/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Publisher_Obj.Publisher;
import java.awt.Color;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import Core.*;

/**
 *
 * @author Jayashanka Deshan
 */
public class account_info extends javax.swing.JInternalFrame {

    Socket soc = null;
    
    ObjectInputStream in = null;
    
    ObjectOutputStream out = null;
    
    cache_writer writer = new cache_writer();
    
    cache_reader reader = new cache_reader();
      
    public account_info() 
    {
        initComponents();
                
        try 
         {
            soc = new Socket(reader.reader("ip_address.dat"), 2002);
            
            out = new ObjectOutputStream(soc.getOutputStream());
            
            in = new ObjectInputStream(soc.getInputStream());
            
            mes1.setForeground(Color.green);
            
            mes1.setText("SERVER : Connected");
          }
        
        catch(Exception Error_01)
        {
           mes1.setForeground(Color.red);
                       
           mes1.setText("SERVER : Disconnected");
            
           button.setEnabled(false);
           
           System.out.println(Error_01);
        }
    }
    
    
public class bidding_thread implements Runnable
{
        @Override
        public void run() 
        {

        Publisher info = new Publisher();

        info.C_NAME = name.getText().trim();
        
        info.C_SYMBOL = code.getText().trim();
        
        info.PRICE = price.getText().trim();
        
        info.S_NUMBER = number.getText().trim();
        
        info.PROFIT = profit.getText().trim();
        
        //info.PASSWORD = pwd.getText().trim();
        
        try {
            out.writeObject(info);
            
            String mesg = (String) in.readObject();
            
            System.out.println("SERVER MESSAGE : "+mesg);
            
            mes1.setText(mesg);

            //symbol1.setText("");
            
            writer.writer("Company_Name.dat",name.getText());
            
            writer.writer("Item_Code.dat",code.getText());
            
            writer.writer("Price.dat",price.getText());
            
            writer.writer("Code_Security.dat",number.getText());
            
            writer.writer("Profit.dat",profit.getText());
                                   
            price.setText("");
                        
            price.requestFocus();
            
        } 
        catch (Exception ee) 
        {
            System.out.println("can't send data" + ee);
        }
    }
        
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        code = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        profit = new javax.swing.JTextField();
        number = new javax.swing.JTextField();
        button = new javax.swing.JButton();
        mes1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setPreferredSize(new java.awt.Dimension(1080, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/registered_trademark_30px.png"))); // NOI18N
        jLabel1.setText("Register Your Organization");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 349, 44));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel2.setText("Company Code  : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 132, 164, 41));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel3.setText("Price :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 191, 164, 41));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel5.setText("Company Name : ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 73, 164, 41));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel6.setText("Security Number : ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 164, 41));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel7.setText("Add Profit  : ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 309, 164, 41));

        code.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        code.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));
        getContentPane().add(code, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 137, 255, -1));

        name.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 78, 255, -1));

        price.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        price.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));
        getContentPane().add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 196, 255, -1));

        profit.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        profit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));
        getContentPane().add(profit, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 314, 255, -1));

        number.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        number.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));
        number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberActionPerformed(evt);
            }
        });
        getContentPane().add(number, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 255, 255, -1));

        button.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        button.setForeground(new java.awt.Color(102, 102, 102));
        button.setText("Register");
        button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });
        getContentPane().add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 270, 170, 50));

        mes1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        getContentPane().add(mes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 210, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/5082238.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberActionPerformed

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        
        bidding_thread obj = new bidding_thread();
        
        Thread thread = new Thread(obj);
        
        thread.run();
        
    }//GEN-LAST:event_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button;
    private javax.swing.JTextField code;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel mes1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField number;
    private javax.swing.JTextField price;
    private javax.swing.JTextField profit;
    // End of variables declaration//GEN-END:variables
}
