/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import JDBC.db_conn;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Jayashanka Deshan
 */
public class DB_Management extends javax.swing.JInternalFrame {

    /**
     * Creates new form DB_Management
     */
   Connection conn = null;

   PreparedStatement pst = null;
   
   ResultSet rs = null;
   
    public DB_Management() 
    {
        initComponents();
        
         conn = db_conn.connect();
       
       try
       {
           System.out.print("Data Base OK !!");
           
           status.setText("Connected");
           
           table_load();
       }
       catch(SQLException ex)
       {
           System.out.print("Error Message : "+ex);
           
           status.setText("Something Wrong !!");
       }
    }
    
    public void table_load() throws SQLException // That method load database data to jtable
    {
        String sql = "SELECT * FROM Data";

        pst = conn.prepareStatement(sql);
        
        rs = pst.executeQuery();
        
        table.setModel(DbUtils.resultSetToTableModel(rs));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        securitybox = new javax.swing.JLabel();
        profitbox = new javax.swing.JLabel();
        symbolbox = new javax.swing.JLabel();
        pricebox = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(910, 470));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 504, 450));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel1.setText("Symbol : ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 92, 90, 38));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel2.setText("Security :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 231, 90, 38));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel3.setText("DB Status : ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 24, 90, 38));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel4.setText("Price : ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 90, 38));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel5.setText("Profit :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 299, 90, 38));

        status.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        getContentPane().add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 24, 240, 38));

        securitybox.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        getContentPane().add(securitybox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 231, 184, 38));

        profitbox.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        getContentPane().add(profitbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 299, 184, 38));

        symbolbox.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        getContentPane().add(symbolbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 92, 240, 38));

        pricebox.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        pricebox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));
        getContentPane().add(pricebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 161, 240, 38));

        jButton1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/remove_30px.png"))); // NOI18N
        jButton1.setText("REMOVE");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 120, 50));

        jButton2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update_30px.png"))); // NOI18N
        jButton2.setText("UPDATE");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 120, 50));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mitchell-luo-U1Hhinvb-v4-unsplash.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        
        int row = table.getSelectedRow();
        
        String symbol = table.getValueAt(row,0).toString();
        
        String price = table.getValueAt(row, 1).toString();
        
        String security = table.getValueAt(row,2).toString();
        
        String profit = table.getValueAt(row,3).toString();
        
        symbolbox.setText(symbol);
        
        pricebox.setText(price);
        
        securitybox.setText(security);
        
        profitbox.setText(profit);
    }//GEN-LAST:event_tableMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        int x = JOptionPane.showConfirmDialog(null,"ARE YOU REALLY WANT UPDATE THAT");
        
        if(x == 0)
        {
            String symbol = symbolbox.getText();
            
            String price = pricebox.getText();
            
            
            String sql = "UPDATE Data SET PRICE = '"+price+"' WHERE SYMBOL = '"+symbol+"'";
            
            try
            {
                pst = conn.prepareStatement(sql);
            
                pst.execute();
                
                table_load();
            }
            catch(Exception ex)
            {
                System.out.println("ERROR : "+ex);
            }

        }
        else if(x == 1)
        {
            
        }
        else if(x == 2)
        {
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
          int x = JOptionPane.showConfirmDialog(null,"ARE YOU REALLY WANT REMOVE THAT");
        
        if(x == 0)
        {
            String symbol = symbolbox.getText();
                        
            String sql = "DELETE FROM Data WHERE SYMBOL = '"+symbol+"'";
            
            try
            {
                pst = conn.prepareStatement(sql);
            
                pst.execute();
                
                table_load();
            }
            catch(Exception ex)
            {
                System.out.println("ERROR : "+ex);
            }

        }
        else if(x == 1)
        {
            
        }
        else if(x == 2)
        {
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pricebox;
    private javax.swing.JLabel profitbox;
    private javax.swing.JLabel securitybox;
    private javax.swing.JLabel status;
    private javax.swing.JLabel symbolbox;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
