
package Interfaces;

import Services.*;

import JDBC.db_conn;

import Server.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import java.sql.Connection;

import java.sql.DriverManager;

import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.swing.Timer;


public class My_Server extends javax.swing.JInternalFrame {

    Connection conn = null;
    
    Timer timer;
    
    public My_Server() 
    {
        initComponents();
        
        try
        {
        connection connect = new connection();
        
        net.setText(connect.net_connection());
        
        get_ip address = new get_ip();
        
        ip.setText(address.get_ip_address());
        
        table_send get = new table_send();
        
        port.setText(get.access_port());
        
        Current_Date today = new Current_Date();
        
        date.setText(today.date());
                
        }
        
        catch(Exception ex)
        {
            
        
        }
        
        try
        {
            String databaseURL = "jdbc:ucanaccess://Stock_Market_Database.accdb";

            conn = DriverManager.getConnection(databaseURL);

            System.out.println("Connected!!");
            
            base.setText("CONNECTED!!");

        }
        catch (Exception e)
        {
            
            System.out.println("DB Fail To Connect \nError : "+e);
            
            base.setText("DISCONNECTED!!");
        }
        
        
        ActionListener actionListener = new ActionListener() 
        {
            @Override
            public void actionPerformed(ActionEvent e) 
            {
                Date date = new Date();
                
                DateFormat timeFormat = new SimpleDateFormat("HH:mm:ss");
                
                String time = timeFormat.format(date);
                
                time_zone.setText(time);
                
            }
        };
        
        timer = new Timer(1000, actionListener);
        
        timer.setInitialDelay(0);
        
        timer.start();
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        port = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        time_zone = new javax.swing.JTextField();
        ip = new javax.swing.JTextField();
        base = new javax.swing.JTextField();
        net = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(910, 470));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 20)); // NOI18N
        jLabel1.setText("Time   : ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 75, -1, 45));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 20)); // NOI18N
        jLabel2.setText("IP Address : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 139, 115, 45));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 20)); // NOI18N
        jLabel3.setText("Port Address : ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 267, -1, 45));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 20)); // NOI18N
        jLabel4.setText("Network Connection  : ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 331, -1, 45));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 20)); // NOI18N
        jLabel5.setText("DataBase Status   : ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 203, -1, 45));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 20)); // NOI18N
        jLabel6.setText("Date   : ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 11, -1, 45));

        port.setEditable(false);
        port.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        port.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));
        getContentPane().add(port, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 268, 249, 45));

        date.setEditable(false);
        date.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        date.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 12, 249, 45));

        time_zone.setEditable(false);
        time_zone.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        time_zone.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));
        getContentPane().add(time_zone, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 76, 249, 45));

        ip.setEditable(false);
        ip.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        ip.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));
        getContentPane().add(ip, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 140, 249, 45));

        base.setEditable(false);
        base.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        base.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));
        getContentPane().add(base, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 204, 249, 45));

        net.setEditable(false);
        net.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        net.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));
        getContentPane().add(net, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 332, 249, 45));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1586388.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField base;
    private javax.swing.JTextField date;
    private javax.swing.JTextField ip;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField net;
    private javax.swing.JTextField port;
    private javax.swing.JTextField time_zone;
    // End of variables declaration//GEN-END:variables
}
